name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    runs-on: arc-runners

    container:
      image: docker pull ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        shell: bash
        run: |
          just

  miri:
    runs-on: arc-runners

    container:
      image: docker pull ghcr.io/facet-rs/facet-ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run miri
        shell: bash
        run: |
          just miri
